# Default values for dacat-api-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: dacat/oai-provider-service
  tag: latest
  pullPolicy: Always
service:
  name: oai
  type: NodePort
  externalPort: 80
  internalPort: 3000
ingress:
  enabled: true
  # Used to create an Ingress record.
  # this will be extended by environment within yaml file
  # TODO: change service name to include environment ?
  host: scicat01.esss.lu.se

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
